server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cafe"
    username: "user"
    password: "password"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  liquibase:
    changeLog: "classpath:/db/changelog/db.changelog-master.xml"
